/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/message/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Message */
        get: operations["get_message_api_message__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Initial Game State */
        get: operations["get_initial_game_state_api_state_init_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardState */
        CardState: {
            /** Action Used */
            action_used: boolean;
            /** Num Resources */
            num_resources: number;
            /** Resources Can Be Taken */
            resources_can_be_taken: boolean;
        };
        /** GameState */
        GameState: {
            /** All Cards */
            all_cards: string[];
            /** Board State */
            board_state: {
                [key: string]: components["schemas"]["TileState"];
            };
            /** Cur Generation */
            cur_generation: number;
            /** Deck */
            deck: string[];
            generation_state: components["schemas"]["GenerationState"];
            /** Global Parameter Progress */
            global_parameter_progress: {
                [key: string]: number;
            };
            /** Global Parameter Targets */
            global_parameter_targets: {
                [key: string]: number;
            };
            /** Player State */
            player_state: components["schemas"]["PlayerState"][];
        };
        /** GenerationState */
        GenerationState: {
            /** First Player */
            first_player: number;
            /** Passed */
            passed: boolean[];
            phase: components["schemas"]["Phase"];
        };
        /**
         * GlobalParameter
         * @enum {string}
         */
        GlobalParameter: "ocean" | "oxygen" | "temperature";
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "turn_order" | "research" | "action" | "production" | "final_production" | "final_greenery";
        /** PlayerState */
        PlayerState: {
            /** Corporation */
            corporation: string | null;
            /** Hand */
            hand: string[];
            /** Production */
            production: {
                [key: string]: number;
            };
            /** Resources */
            resources: {
                [key: string]: number;
            };
            /** Tableau */
            tableau: {
                [key: string]: components["schemas"]["CardState"];
            };
            /** Terraform Rating */
            terraform_rating: number;
        };
        /**
         * Resource
         * @enum {string}
         */
        Resource: "mega_credits" | "steel" | "titanium" | "plant" | "energy" | "heat";
        /** TileState */
        TileState: {
            /** Owner */
            owner: number | null;
            /** Reserved By */
            reserved_by: number | null;
            tile: components["schemas"]["TileType"] | null;
        };
        /**
         * TileType
         * @enum {string}
         */
        TileType: "city" | "greenery" | "ocean" | "special";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_message_api_message__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    get_initial_game_state_api_state_init_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
        };
    };
}
